// <auto-generated />
namespace WebIncidencias_UF3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fechacierrenull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fechacierrenull));
        
        string IMigrationMetadata.Id
        {
            get { return "201704031747307_fecha-cierrenull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
